<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 /home/james/gltf-test/static/models/Cowboy_Male.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName =
    | 'Death'
    | 'Defeat'
    | 'Idle'
    | 'Jump'
    | 'PickUp'
    | 'Punch'
    | 'RecieveHit'
    | 'Roll'
    | 'Run'
    | 'Run_Carry'
    | 'Shoot_OneHanded'
    | 'SitDown'
    | 'StandUp'
    | 'SwordSlash'
    | 'Victory'
    | 'Walk'
    | 'Walk_Carry'
  type GLTFResult = {
    nodes: {
      Cube004: THREE.SkinnedMesh
      Cube004_1: THREE.SkinnedMesh
      Cube004_2: THREE.SkinnedMesh
      Cube004_3: THREE.SkinnedMesh
      Cube004_4: THREE.SkinnedMesh
      Cube004_5: THREE.SkinnedMesh
      Cube004_6: THREE.SkinnedMesh
      Cube004_7: THREE.SkinnedMesh
      Cube004_8: THREE.SkinnedMesh
      Bone: THREE.Bone
    }
    materials: {
      Skin: THREE.MeshStandardMaterial
      Jacket: THREE.MeshStandardMaterial
      Top: THREE.MeshStandardMaterial
      Scarf: THREE.MeshStandardMaterial
      HatBrown: THREE.MeshStandardMaterial
      Pants: THREE.MeshStandardMaterial
      Face: THREE.MeshStandardMaterial
      HatLightBrown: THREE.MeshStandardMaterial
      Hair: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Cowboy_Male.gltf')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="CharacterArmature">
        <T is={gltf.nodes.Bone} />
        <T.Group name="Body_1">
          <T.SkinnedMesh
            name="Cube004"
            geometry={gltf.nodes.Cube004.geometry}
            material={gltf.materials.Skin}
            skeleton={gltf.nodes.Cube004.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_1"
            geometry={gltf.nodes.Cube004_1.geometry}
            material={gltf.materials.Jacket}
            skeleton={gltf.nodes.Cube004_1.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_2"
            geometry={gltf.nodes.Cube004_2.geometry}
            material={gltf.materials.Top}
            skeleton={gltf.nodes.Cube004_2.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_3"
            geometry={gltf.nodes.Cube004_3.geometry}
            material={gltf.materials.Scarf}
            skeleton={gltf.nodes.Cube004_3.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_4"
            geometry={gltf.nodes.Cube004_4.geometry}
            material={gltf.materials.HatBrown}
            skeleton={gltf.nodes.Cube004_4.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_5"
            geometry={gltf.nodes.Cube004_5.geometry}
            material={gltf.materials.Pants}
            skeleton={gltf.nodes.Cube004_5.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_6"
            geometry={gltf.nodes.Cube004_6.geometry}
            material={gltf.materials.Face}
            skeleton={gltf.nodes.Cube004_6.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_7"
            geometry={gltf.nodes.Cube004_7.geometry}
            material={gltf.materials.HatLightBrown}
            skeleton={gltf.nodes.Cube004_7.skeleton}
          />
          <T.SkinnedMesh
            name="Cube004_8"
            geometry={gltf.nodes.Cube004_8.geometry}
            material={gltf.materials.Hair}
            skeleton={gltf.nodes.Cube004_8.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
